tabela = ('Palmeiras','Internacional','Fluminense','Corinthians','Flamengo','Athletico-PR','Atletico-MG','Fortaleza','São Paulo',' América-MG','Botafogo','Santos','Goiás','Bragantino','Coritiba','Cuiabá','CearáSC','Atlético-GO','Avaí','Juventude')
print('-=' * 40)
print(f'Lista de times do Brasileirão: {tabela} ')
print('=-' * 40)
print(f'Os 5 primeiros são: {tabela[0:5]}')
print('=-' * 40)
print(f'Os 4 últimos são: {tabela[-4:]}')
print('=-' * 40)
print(f'Times em ordem alfabética: {sorted(tabela)}')
print('=-' * 40)
print(f'O {tabela[7]} está na 8º posição')
